### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by mukeshkabra** [vbanthia/appium-docker-test#2]
while running from docker as steps you mention 
i am getting this error 

/usr/local/bundle/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/response.rb:73:in `assert_ok': status code 500 (Selenium::WebDriver::Error::ServerError)
Can you help me for this

**Comment by vbanthia-zz** [comment]
Above error only says that it is Appium Server internal error. May be the test which I wrote are failing on your device or Android Version. 

Please provide more information detailing your environment and steps you used to run this demo. And at what point this error was raised?

**Comment by z-ji** [comment]
I have the same error when first running the project by

`docker run --privileged -v /dev/bus/usb:/dev/bus/usb -e "DEVICE_SERIAL=appium_device_serial" -e "FEATURE=addition" --name device1-addition vbanthia/appium-docker-test:latest`

I'm runing in Fedora 25 and Docker version 1.12.5, build 03508cc/1.12.5, and the detail stacktrace is:


```
Digest: sha256:a6deb0693262477322c2325d7f1ae316799c25053d371dc51681d2306c787732
Status: Downloaded newer image for docker.io/vbanthia/appium-docker-test:latest
Starting appium server
Running addition tests
/usr/local/bin/ruby -I/usr/local/bundle/gems/rspec-core-3.4.1/lib:/usr/local/bundle/gems/rspec-support-3.4.1/lib /usr/local/bundle/gems/rspec-core-3.4.1/exe/rspec spec/features/addition_spec.rb

Finished in 30.25 seconds (files took 0.21155 seconds to load)
0 examples, 0 failures

/usr/local/bundle/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/response.rb:73:in `assert_ok': status code 500 (Selenium::WebDriver::Error::ServerError)
	from /usr/local/bundle/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
	from /usr/local/bundle/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/http/common.rb:78:in `new'
	from /usr/local/bundle/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/http/common.rb:78:in `create_response'
	from /usr/local/bundle/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/http/default.rb:90:in `request'
	from /usr/local/bundle/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
	from /usr/local/bundle/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/bridge.rb:664:in `raw_execute'
	from /usr/local/bundle/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/bridge.rb:122:in `create_session'
	from /usr/local/bundle/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/bridge.rb:87:in `initialize'
	from /usr/local/bundle/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/common/driver.rb:56:in `new'
	from /usr/local/bundle/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/common/driver.rb:56:in `for'
	from /usr/local/bundle/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver.rb:86:in `for'
	from /usr/local/bundle/gems/appium_lib-8.0.0/lib/appium_lib/driver.rb:484:in `start_driver'
	from /usr/src/spec/spec_helper.rb:25:in `block (2 levels) in <top (required)>'
	from /usr/local/bundle/gems/rspec-core-3.4.1/lib/rspec/core/example.rb:424:in `instance_exec'
	from /usr/local/bundle/gems/rspec-core-3.4.1/lib/rspec/core/example.rb:424:in `instance_exec'
	from /usr/local/bundle/gems/rspec-core-3.4.1/lib/rspec/core/hooks.rb:357:in `run'
	from /usr/local/bundle/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1724:in `block in run_hooks_with'
	from /usr/local/bundle/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1724:in `each'
	from /usr/local/bundle/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1724:in `run_hooks_with'
	from /usr/local/bundle/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1679:in `with_suite_hooks'
	from /usr/local/bundle/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:114:in `block in run_specs'
	from /usr/local/bundle/gems/rspec-core-3.4.1/lib/rspec/core/reporter.rb:77:in `report'
	from /usr/local/bundle/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:113:in `run_specs'
	from /usr/local/bundle/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:89:in `run'
	from /usr/local/bundle/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:73:in `run'
	from /usr/local/bundle/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:41:in `invoke'
	from /usr/local/bundle/gems/rspec-core-3.4.1/exe/rspec:4:in `<main>'
/usr/local/bin/ruby -I/usr/local/bundle/gems/rspec-core-3.4.1/lib:/usr/local/bundle/gems/rspec-support-3.4.1/lib /usr/local/bundle/gems/rspec-core-3.4.1/exe/rspec spec/features/addition_spec.rb failed
```
